export const seoContent = {
  en: {
    description:
      'Luis Farfan - Experienced Tech Lead & Full-Stack Software Engineer. Expert in scalable web applications, team leadership, and delivering high-impact solutions for enterprise clients. Bilingual professional with remote work expertise.',
    keywords: [
      'Luis Farfan',
      'Tech Lead',
      'Full-Stack Engineer',
      'Software Engineer',
      'React Developer',
      'Node.js Developer',
      'Next.js Expert',
      'JavaScript Developer',
      'TypeScript Developer',
      'Team Leadership',
      'Software Architecture',
      'Web Development',
      'Frontend Developer',
      'Backend Developer',
      'Software Development',
      'Guatemala Developer',
      'Remote Developer',
      'Scalable Applications',
      'Enterprise Solutions',
      'Software Consultant',
      'Bilingual Developer',
      'English Spanish Developer',
      'International Developer',
      'Remote Work Expert',
      'Cross-cultural Communication',
      'Global Software Solutions',
    ],
  },
  es: {
    description:
      'Luis Farfan - Líder Técnico y Desarrollador Full-Stack con experiencia. Experto en aplicaciones web escalables, liderazgo de equipos y soluciones de alto impacto para clientes empresariales. Profesional bilingüe con experiencia en trabajo remoto.',
    keywords: [
      'Luis Farfan',
      'Líder Técnico',
      'Desarrollador Full-Stack',
      'Ingeniero de Software',
      'Desarrollador React',
      'Desarrollador Node.js',
      'Experto Next.js',
      'Desarrollador JavaScript',
      'Desarrollador TypeScript',
      'Liderazgo de Equipos',
      'Arquitectura de Software',
      'Desarrollo Web',
      'Desarrollador Frontend',
      'Desarrollador Backend',
      'Desarrollo de Software',
      'Desarrollador Guatemala',
      'Desarrollador Remoto',
      'Aplicaciones Escalables',
      'Soluciones Empresariales',
      'Consultor de Software',
      'Desarrollador Bilingüe',
      'Desarrollador Inglés Español',
      'Desarrollador Internacional',
      'Experto Trabajo Remoto',
      'Comunicación Intercultural',
      'Soluciones Software Globales',
    ],
  },
};
